{{- if .Values.envs.secret.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ecc-service.fullname" . }}-env-secret
data:
  {{- with .Values.envs.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end}}


{{- if .Values.volumes.secret.enabled }}
{{- range $i,$volume := .Values.volumes.secret.configs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecc-service.fullname" $ }}-vol{{ $i }}-secret
  labels:
    app.kubernetes.io/name: {{ include "ecc-service.name" $ }}
    helm.sh/chart: {{ include "ecc-service.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
---
{{- end }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "harbor-ops" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-ops
  labels:
    app.kubernetes.io/managed-by: Helm  
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5Lm9wcy5lY2xpbmNsb3VkLm5ldC8iOnsidXNlcm5hbWUiOiJkZXZvcHMtcnciLCJwYXNzd29yZCI6ImkzVnh3czR6WTUifX19
---
{{- end }}
