apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ecc-service.labels" . | nindent 4 }}
    # SpringBoot 的 actuator 指标采集
    {{- if .Values.actuatorExporter.enabled }}
    app: actuator-exporter
    {{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- range .Values.service.extend -}}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{  default "TCP" .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "ecc-service.selectorLabels" . | nindent 4 }}
    
