actuatorExporter:
  enabled: true

replicaCount: 1
service:
  type: ClusterIP
  port: 8080
ingresses:
  - className: "ecc-internal"
    cloud: "tecentcloud"
    class: nginx
    annotations: {}
    tlsEnabled: false
resources:
  requests:
    cpu: 50m
    memory: 1536Mi
  limits:
    cpu: 1000m
    memory: 2048Mi
healthCheck:
  enabled: false
  readinessPath: /actuator/health
  livenessPath: /actuator/health
nacos:
  enabled: true
  data:
    SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: nacos-hs.nacos:8848
    SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: ecc
    SPRING_CLOUD_NACOS_CONFIG_GROUP: DEFAULT_GROUP
    SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos-hs.nacos:8848
    SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: ecc
    SPRING_CLOUD_NACOS_DISCOVERY_GROUP: DEFAULT_GROUP
envs:
  customer:
    enabled: true
    data:
      # # 容器启动端口，代码中默认为 8080；可在 nacos 中可设置 server.port: 8080,也可在此设置环境变量, APP_SERVICE_NAME用于postStart和preStop脚本
      # ENV_PROJECT_SERVER_PORT: 8080
      #SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_BOOTSTRAP_ENABLED: true
      APP_SERVICE_NAME: ctms-schedule-provider
      JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=75.0  -XX:+UseG1GC  
lifecycle:
  postStart:
    enabled: true
  preStop:
    enabled: true
volumes:
  pvc:
    enabled: true
    type: shared
    static: true
    configs:
      ## 客户在ET，RM，CT系统数据导出后的下载目录，后期可能其他子系统也会开通下载功能
      - mountPath: /data/eclincloud/downloads
        accessModes:
          - ReadWriteMany
        storageSize: 10G
        storageClassName: ecc-sc-nfs-shared-default
        ###   if pv static
        pvFsid: "738m76f6"
        pvHost: "10.10.2.100"
        subPath: "ctms-downloads"
